repos:
  - repo: local
    hooks:
      - id: tests
        name: tests
        entry: python -m unittest discover tests/
        language: system
        always_run: false
        pass_filenames: false
        files: \.(py.|cpp|c)$
      - id: ruff
        name: ruff
        entry: ruff check
        language: system
        always_run: false
        pass_filenames: false
        files: \.py.$