repos:
  - repo: local
    hooks:
      - id: tests
        name: tests
        entry: python -m unittest discover tests/
        language: system
        always_run: true
        pass_filenames: false