repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8 --statistics -j4
        language: system
        always_run: true
        pass_filenames: false
      - id: tests
        name: tests
        entry: python -m unittest discover tests/
        language: system
        always_run: true
        pass_filenames: false