line-length = 150
indent-width = 2
target-version = "py311"
preview = true

lint.select = [
    "F",
    "W293",
    "W291",
    "W191",
    "W292",
    "W391",
    "E703",
    "E999"
]

include = [
    "streamtasks/*.py",
    "tests/**.py",
    "extra/**.py",
    "examples/**.py",
]