name: Release

on: workflow_dispatch

jobs:
  build-sdist:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Build web assets
        run: pnpm install && pnpm -r build:prod

      - name: Build the package
        run: python -m build -s
        
      - name: Upload sdist artifact
        uses: actions/upload-artifact@v4
        with:
          name: py-sdist
          path: dist
      
      - name: Upload web assets artifact
        uses: actions/upload-artifact@v4
        with:
          name: webassets
          path: streamtasks/system/assets

  build-wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    needs: [build-sdist]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
    steps:
      - uses: actions/checkout@v4
      - name: Download web assets artifact
        uses: actions/download-artifact@v4
        with:
          name: webassets
          path: streamtasks/system/assets
      - uses: actions/setup-python@v5
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.19.2
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  merge-pypackage:
    name: Merge package data
    needs: [build-sdist, build-wheels]
    runs-on: ubuntu-latest
    steps:
      - name: Download sdist artifact
        uses: actions/download-artifact@v4
        with:
          name: py-sdist
          path: dist
      - name: Download wheelhouse artifact
        uses: actions/download-artifact@v4
        with:
          pattern: 'cibw-wheels-*'
          path: wheelhouse
      - name: move wheels
        run: find wheelhouse/ -type f -name "streamtasks*.whl" -exec cp {} ./dist \;
      - name: Upload Python package artifact
        uses: actions/upload-artifact@v4
        with:
          name: pypackage
          path: dist

  publish-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [merge-pypackage]
    timeout-minutes: 20
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download Python package artifact
        uses: actions/download-artifact@v4
        with:
          name: pypackage
          path: dist

      - name: Extract version from pyproject.toml
        id: extract_version
        run: echo "version=$(find dist/streamtasks*.tar.gz | sed -E 's/.*streamtasks-([0-9\.]+)\.tar\.gz/\1/')" >> $GITHUB_OUTPUT

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          tag_name: ${{ steps.extract_version.outputs.version }}
          name: Release ${{ steps.extract_version.outputs.version }}
          body: Release ${{ steps.extract_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  publish-to-pypi:
    name: publish python distribution to PyPI
    needs: [merge-pypackage]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/streamtasks
    permissions:
      id-token: write
    steps:
    - name: Download Python package artifact
      uses: actions/download-artifact@v4
      with:
        name: pypackage
        path: dist/
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1