name: unit tests and linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache apt packages
      id: cache-apt
      uses: actions/cache@v3
      with:
        expire-after: 7d
        path: /var/cache/apt/archives
        key: ${{ runner.os }}-apt-${{ hashFiles('apt-dependencies.txt') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    - name: Install system dependencies
      if: steps.cache-apt.outputs.cache-hit != 'true'
      run: |
        sudo apt update -y
        sudo apt install portaudio19-dev ffmpeg -y

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev,media,testing]

    - name: Run tests
      env:
        FULL: 1
        DEBUG_SER: 1
        DATA_DIR: .data
      run: |
        python -m unittest discover tests/ -v

    - name: Run ruff linter
      run: |
        ruff check .