name: unit tests and linting

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install system dependencies
      run: |
        apt update -y
        apt install portaudio19-dev ffmpeg -y

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev,media,testing]

    - name: Run tests
      env:
        FULL: 1
        DEBUG_SER: 1
      run: |
        python -m unittest discover tests/

    - name: Run ruff linter
      run: |
        ruff check .